Repository highsource/jaxb-tools, pull requests merged in 2023-09, with the labels that each got.

#353 [#188] Classloaders not being closed for mojo classloader
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/util/IOUtils.java
Labels: enhancement

#358 fix javadoc
  README.md
  hyperjaxb/ejb/plugin/src/main/java/org/jvnet/hyperjaxb3/ejb/strategy/customizing/Customizing.java
  hyperjaxb/ejb/plugin/src/main/java/org/jvnet/hyperjaxb3/ejb/strategy/model/CreatePropertyInfos.java
  hyperjaxb/ejb/schemas/persistence/pom.xml
  hyperjaxb/maven/plugin/src/main/java/org/jvnet/hyperjaxb3/maven2/Hyperjaxb3Mojo.java
  pom.xml
Labels: bug, documentation

#363 [#100] Fixing eclipse errors reading directory as project resource
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
Labels: bug, maven-plugin

#361 [#19] Fix relative Catalog Resolution
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJC2Mojo.java
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/RelativeCatalog.java
  maven-plugin/tests/gh-issue-19/pom.xml
  maven-plugin/tests/pom.xml
Labels: bug, maven-plugin

#368 update README
  README.md
Labels: documentation

#373 GH-366 : re-enable gh-issue-19 project
  hyperjaxb/ejb/samples/po-customized-toplink/project-build.xml
  hyperjaxb/ejb/samples/po-initial/project-build.xml
  hyperjaxb/ejb/samples/pom.xml
  hyperjaxb/ejb/samples/uniprot/project-build.xml
  hyperjaxb/ejb/templates/basic/project-build.xml
  maven-plugin/plugin-core/pom.xml
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJC2Mojo.java
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/ClasspathCatalogResolver.java
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/MavenCatalogResolver.java
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/resolver/tools/RelativeCatalog.java
  maven-plugin/plugin-core/src/test/java/org/jvnet/jaxb/maven/resolver/tools/tests/MavenCatalogResolverTest.java
  maven-plugin/tests/gh-issue-19/b/pom.xml
  maven-plugin/tests/gh-issue-19/b/src/main/resources/b/b.cat
  maven-plugin/tests/gh-issue-19/pom.xml
  maven-plugin/tests/pom.xml
Labels: bug

#396 Issue 395 : add option to generate default-attribute-value in java class
  jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/defaultvalueplugin/DefaultValuePlugin.java
  jaxb-plugins-parent/tests/defaultvalue/pom.xml
  jaxb-plugins-parent/tests/defaultvalue/src/main/resources/Person.xsd
Labels: enhancement

#398 [#397] Remove of deprecated params and classed
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/CopyStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/CopyStrategy2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/CopyTo.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/CopyTo2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/DefaultCopyStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/DefaultEqualsStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/DefaultHashCodeStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/DefaultMergeStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/DefaultToStringStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/Equals.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/Equals2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/EqualsStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/EqualsStrategy2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/HashCode.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/HashCode2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/HashCodeStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/HashCodeStrategy2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/JAXBCopyStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/JAXBEqualsStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/JAXBHashCodeStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/JAXBMergeCollectionsStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/JAXBMergeStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/JAXBToStringStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/MergeFrom.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/MergeFrom2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/MergeStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/MergeStrategy2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/ToString.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/ToString2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/ToStringStrategy.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/main/java/org/jvnet/jaxb/lang/ToStringStrategy2.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/test/java/org/jvnet/jaxb/lang/tests/CopyStrategyTest.java
  jaxb-plugins-parent/jaxb-plugins-runtime/src/test/java/org/jvnet/jaxb/lang/tests/CyclicTests.java
  jaxb-plugins-parent/jaxb-plugins-testing/src/main/java/org/jvnet/jaxb/lang/ExtendedJAXBEqualsStrategy.java
  jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/copyable/CopyablePlugin.java
  jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/equals/EqualsPlugin.java
  jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/hashcode/HashCodePlugin.java
  jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/mergeable/MergeablePlugin.java
  jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/simpletostring/SimpleToStringPlugin.java
  jaxb-plugins-parent/jaxb-plugins/src/main/java/org/jvnet/jaxb/plugin/tostring/ToStringPlugin.java
  jaxb-plugins-parent/tests/issues/src/test/java/org/jvnet/jaxb/tests/issues/CopyableTest.java
  jaxb-plugins-parent/tests/issues/src/test/java/org/jvnet/jaxb/tests/issues/GH31Test.java
  jaxb-plugins-parent/tests/issues/src/test/java/org/jvnet/jaxb/tests/issues/GH37Test.java
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/AbstractXJCMojo.java
  maven-plugin/plugin-core/src/main/java/org/jvnet/jaxb/maven/RawXJCMojo.java
Labels: enhancement
